# Translations template for vigilo-correlator.
# Copyright (C) 2020 ORGANIZATION
# This file is distributed under the same license as the vigilo-correlator
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2020.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: vigilo-correlator 5.0.1\n"
"Report-Msgid-Bugs-To: contact.vigilo@c-s.fr\n"
"POT-Creation-Date: 2020-07-09 11:53+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.5.1\n"

#: src/vigilo/correlator/__init__.py:33
msgid "The topology has been reloaded."
msgstr ""

#: src/vigilo/correlator/__init__.py:53
msgid ""
"Could not set signal handlers. The correlator may not be able to shutdown "
"cleanly"
msgstr ""

#: src/vigilo/correlator/correvent.py:138
#, python-format
msgid ""
"Ignoring request to update correlated event %r: a more recent update already "
"exists in the database"
msgstr ""

#: src/vigilo/correlator/correvent.py:143
#, python-format
msgid "Updating existing correlated event (%r)"
msgstr ""

#: src/vigilo/correlator/correvent.py:146
#, python-format
msgid "Got a reference to a non-existent correlated event (%r), adding as new"
msgstr ""

#: src/vigilo/correlator/correvent.py:189
#, python-format
msgid ""
"Got a reference to a nonexistent correlated event (%r), skipping this "
"aggregate"
msgstr ""

#: src/vigilo/correlator/correvent.py:379
#, python-format
msgid ""
"Creating new aggregate with cause #%(cause)d (#%(supitem)d) from aggregate "
"#%(original)d"
msgstr ""

#: src/vigilo/correlator/correvent.py:567
#, python-format
msgid ""
"Ignoring event #%(idevent)d on (%(host)r, %(service)r) as requested by the "
"correlation rules"
msgstr ""

#: src/vigilo/correlator/correvent.py:593
#, python-format
msgid "Raw event ignored. Reason: status = %r"
msgstr ""

#: src/vigilo/correlator/correvent.py:610
msgid "Creating a new correlated event"
msgstr ""

#: src/vigilo/correlator/db_insertion.py:55
#, python-format
msgid "Received request to add an event on HLS \"%s\""
msgstr ""

#: src/vigilo/correlator/db_insertion.py:60
#, python-format
msgid ""
"Got a reference to a non configured item (%(host)r, %(service)r), skipping "
"event"
msgstr ""

#: src/vigilo/correlator/db_insertion.py:74
#, python-format
msgid ""
"Got a notification about an UNKNOWN state for service \"%(service)s\" on "
"unreachable host \"%(host)s\", skipping event"
msgstr ""

#: src/vigilo/correlator/db_insertion.py:150
#, python-format
msgid ""
"Ignoring request to create a new event with state \"%s\" (nothing alarming "
"here)"
msgstr ""

#: src/vigilo/correlator/db_insertion.py:157
msgid "Creating new event"
msgstr ""

#: src/vigilo/correlator/db_insertion.py:165
#, python-format
msgid "Multiple raw events found (%s), using the first one available."
msgstr ""

#: src/vigilo/correlator/db_insertion.py:170
#, python-format
msgid "Updating event %r"
msgstr ""

#: src/vigilo/correlator/db_insertion.py:229
#, python-format
msgid "Got a reference to a non configured high-level service (%(service)r)"
msgstr ""

#: src/vigilo/correlator/db_insertion.py:256
#, python-format
msgid ""
"Got a reference to a non configured item (%(host)r, %(service)r), skipping "
"state"
msgstr ""

#: src/vigilo/correlator/db_insertion.py:332
#, python-format
msgid "Adding event #%(event)d (supitem #%(supitem)d) to aggregate #%(aggregate)d"
msgstr ""

#: src/vigilo/correlator/db_insertion.py:348
#, python-format
msgid ""
"Event #%(event)d already belongs to aggregate #%(aggregate)d, refusing to add"
" it twice"
msgstr ""

#: src/vigilo/correlator/db_insertion.py:399
#, python-format
msgid "Merging aggregate #%(src)d into aggregate #%(dest)d"
msgstr ""

#: src/vigilo/correlator/db_insertion.py:470
#: src/vigilo/correlator/db_insertion.py:475
msgid "Got a reference to a nonexistent aggregate, aborting"
msgstr ""

#: src/vigilo/correlator/db_insertion.py:487
#, python-format
msgid ""
"Event #%(event)d (supitem #%(supitem)d) will be merged into aggregate "
"#%(aggregate)d"
msgstr ""

#: src/vigilo/correlator/handle_ticket.py:35
#, python-format
msgid ""
"handle_ticket: Trouble ticket message received. Timestamp = %(timestamp)r. "
"Impacted HLS = %(hls)r. Ticket id = %(ticket_id)r. acknowledgement_status = "
"%(ack_status)r. Message = %(message)r."
msgstr ""

#: src/vigilo/correlator/handle_ticket.py:57
#, python-format
msgid "handle_ticket: No matching trouble ticket found : %r"
msgstr ""

#: src/vigilo/correlator/handle_ticket.py:63
#, python-format
msgid "handle_ticket: Several events seem to be associated with this ticket : %r"
msgstr ""

#: src/vigilo/correlator/handle_ticket.py:66
#, python-format
msgid ""
"handle_ticket: The event %(event_id)r is associated with the given ticket "
"(%(ticket_id)r)"
msgstr ""

#: src/vigilo/correlator/handle_ticket.py:88
#, python-format
msgid "handle_ticket: Got exception while updating event %r history"
msgstr ""

#: src/vigilo/correlator/handle_ticket.py:92
#, python-format
msgid "handle_ticket: Event %r history updated successfully."
msgstr ""

#: src/vigilo/correlator/memcached_connection.py:65
#, python-format
msgid "Connected to memcached (%s)"
msgstr ""

#: src/vigilo/correlator/memcached_connection.py:82
#, python-format
msgid "Connecting to memcached server (%s)..."
msgstr ""

#: src/vigilo/correlator/memcached_connection.py:91
#, python-format
msgid "Connection to memcached (%(conn)s) lost: %(reason)s"
msgstr ""

#: src/vigilo/correlator/memcached_connection.py:104
#, python-format
msgid "Connection to memcached (%(conn)s) failed: %(reason)s"
msgstr ""

#: src/vigilo/correlator/memcached_connection.py:242
#, python-format
msgid "Trying to set value '%(value)s' for key '%(key)s' (transaction=%(txn)r)."
msgstr ""

#: src/vigilo/correlator/memcached_connection.py:285
#, python-format
msgid "Trying to get the value of the key '%(key)s' (transaction=%(txn)r)."
msgstr ""

#: src/vigilo/correlator/memcached_connection.py:318
#, python-format
msgid "Trying to delete the key '%(key)s' (transaction=%(txn)r)."
msgstr ""

#: src/vigilo/correlator/registry.py:59
#, python-format
msgid ""
"Rule %(name)s (%(class)s) has already been registered, ignoring attempt to "
"re-register it."
msgstr ""

#: src/vigilo/correlator/registry.py:70
#, python-format
msgid "Cyclic dependencies found: %(path)s"
msgstr ""

#: src/vigilo/correlator/registry.py:79
#, python-format
msgid "Successfully registered rule %r"
msgstr ""

#: src/vigilo/correlator/registry.py:144
msgid ""
"Singleton has already been instanciated, ignoring attempt to create a new "
"instance."
msgstr ""

#: src/vigilo/correlator/registry.py:188
#, python-format
msgid "Not a valid rule name \"%s\""
msgstr ""

#: src/vigilo/correlator/registry.py:194
#, python-format
msgid "Unable to load rule \"%(name)s\" (%(class)s)"
msgstr ""

#: src/vigilo/correlator/registry.py:212
#, python-format
msgid ""
"The rule \"%(rule)s\" depends on the rule \"%(dependency)s\", which has not "
"been loaded."
msgstr ""

#: src/vigilo/correlator/actors/executor.py:87
#, python-format
msgid "Rule %(rule_name)s timed out"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:93
#, python-format
msgid "Unable to contact the database: %s"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:131
msgid "Received invalid item ID (None)"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:144
#, python-format
msgid "Unexpected error: %s"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:167
msgid "Error while modifying the ticket"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:179
msgid "Error while retrieving supervised item ID"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:192
msgid ""
"The rule "
"'vigilo.correlator_enterprise.rules.hls_deps:HighLevelServiceDepsRule' must "
"be loaded for computation orders to be handled properly."
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:202
#: src/vigilo/correlator/actors/rule_dispatcher.py:287
msgid "The connection to memcached timed out. The message will be handled once more."
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:308
msgid "Inserting state"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:310
msgid "Error while saving state"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:330
msgid "Inserting an entry in the HLS history"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:332
msgid "Error while adding an entry in the HLS history"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:337
msgid "Inserting an entry in the history"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:339
msgid "Error while adding an entry in the history"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:353
msgid "Actual correlation"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:387
#, python-format
msgid "Correlation process ended (%.4fs)"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:405
msgid "Handling correlation results"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:424
#, python-format
msgid ""
"Error while saving the correlated event (%s). The message will be handled "
"once more."
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:453
#, python-format
msgid "Correlation failed for message #%(id)s (%(payload)s)"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:473
#, python-format
msgid "Unable to store correlated alert for message #%(id)s (%(payload)s) : %(error)s"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:506
#, python-format
msgid "%s. The message will be handled once more."
msgstr ""

#: src/vigilo/correlator/actors/rule_runner.py:42
#, python-format
msgid ""
"Got an exception while running rule \"%(rule)s\". Running the correlator in "
"the foreground (service vigilo-correlator debug) may help troubleshooting "
"(%(error)s)"
msgstr ""

#: src/vigilo/correlator/rules/example.py:37
#, python-format
msgid "id %(id)s payload %(payload)s"
msgstr ""

#: src/vigilo/correlator/rules/svc_on_host_down.py:48
msgid "Host is down"
msgstr ""

#: src/vigilo/correlator/rules/svc_on_host_down.py:50
#, python-format
msgid "Setting %d services to UNKNOWN"
msgstr ""

#: src/vigilo/correlator/rules/svc_on_host_down.py:117
#, python-format
msgid "Unsupported transition: %(from)s -> %(to)s"
msgstr ""

#: src/vigilo/correlator/rules/svc_on_host_down.py:126
#, python-format
msgid "Asking Nagios for updates on %d services"
msgstr ""

